version: '3.8'

services:
  telegram_bot:
    build: .
    container_name: telegram_bot
    env_file: .env
    volumes:
      - ./downloads:/app/downloads
      - ./data:/app/data
    ports:
      - "8000:8000"
    restart: unless-stopped
